# 5. هندسة الميزات والمعالجة (Feature Engineering & Preprocessing)

In [70]:
import pandas as pd

df = pd.read_csv('train.csv')
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_price,total_freight,...,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state,is_late
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,29.99,8.72,...,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,3149.0,-23.574809,-46.587471,sao paulo,SP,0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,118.70,22.76,...,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,47813.0,-12.169860,-44.988369,barreiras,BA,0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,159.90,19.22,...,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,75265.0,-16.746337,-48.514624,vianopolis,GO,0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,45.00,27.20,...,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,59296.0,-5.767733,-35.275467,sao goncalo do amarante,RN,0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,19.90,8.72,...,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,9195.0,-23.675037,-46.524784,santo andre,SP,0

In [71]:
date_columns = [
    'order_purchase_timestamp', 
    'order_approved_at', 
    'order_delivered_carrier_date', 
    'order_delivered_customer_date', 
    'order_estimated_delivery_date'
]

for col in date_columns:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col])



columns_to_drop = [
    'order_id', 
    'customer_id', 
    'customer_unique_id', 
    'review_id', 
    'review_comment_title', 
    'review_comment_message',
    'geolocation_zip_code_prefix',
    'customer_zip_code_prefix'
]

df = df.drop(columns=[col for col in columns_to_drop if col in df.columns], errors='ignore')

print(df.shape)
df.head()

(69608, 24)

,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_price,total_freight,total_items,total_weight_g,...,review_score,review_creation_date,review_answer_timestamp,customer_city,customer_state,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state,is_late
0,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,29.99,8.72,1.0,500.0,...,4.0,2017-10-11 00:00:00,2017-10-12 03:43:48,sao paulo,SP,-23.574809,-46.587471,sao paulo,SP,0
1,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,118.70,22.76,1.0,400.0,...,4.0,2018-08-08 00:00:00,2018-08-08 18:37:50,barreiras,BA,-12.169860,-44.988369,barreiras,BA,0
2,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,159.90,19.22,1.0,420.0,...,5.0,2018-08-18 00:00:00,2018-08-22 19:07:58,vianopolis,GO,-16.746337,-48.514624,vianopolis,GO,0
3,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,45.00,27.20,1.0,450.0,...,5.0,2017-12-03 00:00:00,2017-12-05 19:21:58,sao goncalo do amarante,RN,-5.767733,-35.275467,sao goncalo do amarante,RN,0
4,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,19.90,8.72,1.0,250.0,...,5.0,2018-02-17 00:00:00,2018-02-18 13:02:51,santo andre,SP,-23.675037,-46.524784,santo andre,SP,0

## حذف القيم الشاذة من التوايخ والتي يكون تاريخ توصيلها قبل تايخ الشحن تبعها وهذا شئ مستحيل واقعيا

In [72]:
dorder_dirv3 = df[(df['order_delivered_customer_date'] - df['order_delivered_carrier_date']).dt.days < 0][[ 'order_delivered_carrier_date', 'order_delivered_customer_date','order_estimated_delivery_date', 'customer_state', 'main_category']]

dorder_dirv3

,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_state,main_category
6438,2017-07-28 16:57:58,2017-07-25 19:32:56,2017-08-14,SP,furniture_decor
9554,2017-07-07 17:22:41,2017-07-06 14:27:51,2017-07-21,MG,furniture_decor
13487,2017-07-20 19:22:02,2017-07-19 14:13:28,2017-08-08,SP,furniture_decor
14474,2017-08-01 18:23:30,2017-07-26 18:09:10,2017-08-11,MG,bed_bath_table
19268,2017-07-20 23:03:42,2017-07-20 18:52:41,2017-07-31,SP,pet_shop
21338,2016-10-26 11:41:53,2016-10-25 17:51:46,2016-11-30,SP,furniture_decor
22520,2017-06-27 14:51:54,2017-06-26 15:45:35,2017-07-14,SP,home_confort
25393,2017-08-10 18:28:56,2017-08-10 18:05:38,2017-08-25,SP,toys
25646,2017-08-01 18:17:47,2017-07-31 17:49:56,2017-08-24,SC,housewares
27470,2017-08-09 18:18:43,2017-08-01 21:13:01,2017-08-18,SP,furniture_decor
34939,2017-03-02 17:34:26,2017-02-14 15:15:57,2017-03-15,MG,garden_tools
41636,2017-02-20 02:32:08,2017-02-15 03:53:46,2017-04-17,SP,bed_bath_table
45302,2017-06-09 15:07:29,2017-06-02 11:09:16,2017-06-23,SP,computers_accessories
49934,2016-10-26 11:43:06,2016-10-20 18:03:17,2016-11-29,SP,furniture_decor
50374,2017-07-14 12:41:34,2017-07-12 20:49:42,2017-08-14,SP,bed_bath_table
58429,2017-08-04 20:04:17,2017-08-03 20:30:00,2017-08-18,SP,consoles_games
68312,2017-07-11 18:15:40,2017-07-11 17:41:26,2017-07-20,SP,auto

In [73]:
delivery_days = (df['order_delivered_customer_date'] - df['order_delivered_carrier_date']).dt.days
df= df[delivery_days >= 0]

## (is_business_hour) بقيم (0 أو 1) بناءً على إذا كانت ساعة الطلب تقع بين 8 صباحاً و 6 مساءً مثلاً.

In [74]:
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])

df['date'] = df['order_purchase_timestamp'].dt.date
df['time'] = df['order_purchase_timestamp'].dt.time

df['order_hour'] = df['order_purchase_timestamp'].dt.hour

def get_time_of_day(hour):
    if 6 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 22:
        return 'Evening'
    else:
        return 'Night'

df['time_of_day'] = df['order_hour'].apply(get_time_of_day)


df['is_business_hour'] = df['order_hour'].between(8, 18).astype(int)

In [75]:
df.head()

,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_price,total_freight,total_items,total_weight_g,...,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state,is_late,date,time,order_hour,time_of_day,is_business_hour
0,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,29.99,8.72,1.0,500.0,...,-23.574809,-46.587471,sao paulo,SP,0,2017-10-02,10:56:33,10,Morning,1
1,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,118.70,22.76,1.0,400.0,...,-12.169860,-44.988369,barreiras,BA,0,2018-07-24,20:41:37,20,Evening,0
2,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,159.90,19.22,1.0,420.0,...,-16.746337,-48.514624,vianopolis,GO,0,2018-08-08,08:38:49,8,Morning,1
3,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,45.00,27.20,1.0,450.0,...,-5.767733,-35.275467,sao goncalo do amarante,RN,0,2017-11-18,19:28:06,19,Evening,0
4,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,19.90,8.72,1.0,250.0,...,-23.675037,-46.524784,santo andre,SP,0,2018-02-13,21:18:39,21,Evening,0

### approval_time_days: تبين كم تأخر المتجر بالموافقة على الطلب.

### processing_time_days: تبين كفاءة التجهيز وتسليمها للشحن.

### shipping_time_days: تبين سرعة شركة الشحن نفسها.

### delivery_vs_estimated_days: توضح ما إذا كان الطلب وصل مبكراً أم متأخراً عن الموعد المتوقع.

In [76]:

# أ. وقت معالجة الطلب والموافقة عليه (من الشراء للموافقة)
df['approval_time_days'] = (df['order_approved_at'] - df['order_purchase_timestamp']).dt.total_seconds() / (24 * 3600)

# ب. وقت التجهيز والشحن للناقل (من الموافقة لتسليمها لشركة الشحن)
df['processing_time_days'] = (df['order_delivered_carrier_date'] - df['order_approved_at']).dt.total_seconds() / (24 * 3600)

# ج. وقت التوصيل الفعلي للزبون (من التسليم للناقل وحتى وصولها للزبون)
df['shipping_time_days'] = (df['order_delivered_customer_date'] - df['order_delivered_carrier_date']).dt.total_seconds() / (24 * 3600)

# د. إجمالي مدة التوصيل (من الشراء وحتى الاستلام الفعلي)
df['total_delivery_days'] = (df['order_delivered_customer_date'] - df['order_purchase_timestamp']).dt.total_seconds() / (24 * 3600)

# هـ. الفرق بين المتوقع والفعلي (مهم جداً لتوقع التأخير)
df['delivery_vs_estimated_days'] = (df['order_estimated_delivery_date'] - df['order_delivered_customer_date']).dt.total_seconds() / (24 * 3600)

In [77]:
df.head()

,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_price,total_freight,total_items,total_weight_g,...,date,time,order_hour,time_of_day,is_business_hour,approval_time_days,processing_time_days,shipping_time_days,total_delivery_days,delivery_vs_estimated_days
0,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,29.99,8.72,1.0,500.0,...,2017-10-02,10:56:33,10,Morning,1,0.007431,2.366493,6.062650,8.436574,7.107488
1,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,118.70,22.76,1.0,400.0,...,2018-07-24,20:41:37,20,Evening,0,1.279745,0.462882,12.039410,13.782037,5.355729
2,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,159.90,19.22,1.0,420.0,...,2018-08-08,08:38:49,8,Morning,1,0.011505,0.204595,9.178113,9.394213,17.245498
3,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,45.00,27.20,1.0,450.0,...,2017-11-18,19:28:06,19,Evening,0,0.012419,3.745833,9.450498,13.208750,12.980069
4,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,19.90,8.72,1.0,250.0,...,2018-02-13,21:18:39,21,Evening,0,0.042940,0.893113,1.937824,2.873877,9.238171

In [78]:
raw_date_columns = [
    'order_purchase_timestamp',
    'order_approved_at', 
    'order_delivered_carrier_date', 
    'order_delivered_customer_date', 
    'order_estimated_delivery_date'
]
df = df.drop(columns=[col for col in raw_date_columns if col in df.columns], errors='ignore')

In [79]:
df.head()

,order_status,total_price,total_freight,total_items,total_weight_g,main_category,seller_state,total_payment,max_installments,review_score,...,date,time,order_hour,time_of_day,is_business_hour,approval_time_days,processing_time_days,shipping_time_days,total_delivery_days,delivery_vs_estimated_days
0,delivered,29.99,8.72,1.0,500.0,housewares,SP,38.71,1.0,4.0,...,2017-10-02,10:56:33,10,Morning,1,0.007431,2.366493,6.062650,8.436574,7.107488
1,delivered,118.70,22.76,1.0,400.0,perfumery,SP,141.46,1.0,4.0,...,2018-07-24,20:41:37,20,Evening,0,1.279745,0.462882,12.039410,13.782037,5.355729
2,delivered,159.90,19.22,1.0,420.0,auto,SP,179.12,3.0,5.0,...,2018-08-08,08:38:49,8,Morning,1,0.011505,0.204595,9.178113,9.394213,17.245498
3,delivered,45.00,27.20,1.0,450.0,pet_shop,MG,72.20,1.0,5.0,...,2017-11-18,19:28:06,19,Evening,0,0.012419,3.745833,9.450498,13.208750,12.980069
4,delivered,19.90,8.72,1.0,250.0,stationery,SP,28.62,1.0,5.0,...,2018-02-13,21:18:39,21,Evening,0,0.042940,0.893113,1.937824,2.873877,9.238171

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 67516 entries, 0 to 69607
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   order_status                67516 non-null  object
 1   total_price                 67516 non-null  float64
 2   total_freight               67516 non-null  float64
 3   total_items                 67516 non-null  float64
 4   total_weight_g              67516 non-null  float64
 5   main_category               66573 non-null  object
 6   seller_state                67516 non-null  object
 7   total_payment               67515 non-null  float64
 8   max_installments            67515 non-null  float64
 9   review_score                67059 non-null  float64
 10  review_creation_date        67059 non-null  object
 11  review_answer_timestamp     67059 non-null  object
 12  customer_city               67516 non-null  object
 13  customer_state              67516 non-null  object
 14  geolocation_lat             67327 non-null  float64
 15  geolocation_lng             67327 non-null  float64
 16  geolocation_city            67327 non-null  object
 17  geolocation_state           67327 non-null  object
 18  is_late                     67516 non-null  int64
 19  date                        67516 non-null  object
 20  time                        67516 non-null  object
 21  order_hour                  67516 non-null  int32
 22  time_of_day                 67516 non-null  object
 23  is_business_hour            67516 non-null  int32
 24  approval_time_days          67504 non-null  float64
 25  processing_time_days        67504 non-null  float64
 26  shipping_time_days          67516 non-null  float64
 27  total_delivery_days         67516 non-null  float64
 28  delivery_vs_estimated_days  67516 non-null  float64
dtypes: float64(14), int32(2), int64(1), object(12)
memory usage: 14.9+ MB

In [81]:
df.isnull().sum()

order_status                    0
total_price                     0
total_freight                   0
total_items                     0
total_weight_g                  0
main_category                 943
seller_state                    0
total_payment                   1
max_installments                1
review_score                  457
review_creation_date          457
review_answer_timestamp       457
customer_city                   0
customer_state                  0
geolocation_lat               189
geolocation_lng               189
geolocation_city              189
geolocation_state             189
is_late                         0
date                            0
time                            0
order_hour                      0
time_of_day                     0
is_business_hour                0
approval_time_days             12
processing_time_days           12
shipping_time_days              0
total_delivery_days             0
delivery_vs_estimated_days      0
dtype: int64

In [82]:
# حساب النسبة المئوية للقيم المفقودة لكل عمود
missing_percentage = (df.isnull().sum() / len(df)) * 100

# تصفية وعرض الأعمدة التي تحتوي على قيم مفقودة فقط مع نسبتها
missing_df = pd.DataFrame({'Missing Count': df.isnull().sum(), 'Percentage (%)': missing_percentage})
missing_df = missing_df[missing_df['Missing Count'] > 0].sort_values(by='Percentage (%)', ascending=False)

print(missing_df)

                         Missing Count  Percentage (%)
main_category                      943        1.396706
review_score                       457        0.676877
review_creation_date               457        0.676877
review_answer_timestamp            457        0.676877
geolocation_lat                    189        0.279934
geolocation_lng                    189        0.279934
geolocation_city                   189        0.279934
geolocation_state                  189        0.279934
approval_time_days                  12        0.017774
processing_time_days                12        0.017774
total_payment                        1        0.001481
max_installments                     1        0.001481

## معالجة القيم الفارغة

In [83]:
initial_rows = len(df)
df = df.dropna()
final_rows = len(df)

print(f"the number of rows dropped : {initial_rows - final_rows}")

the number of rows dropped : 1591

In [84]:
df.isnull().sum()

order_status                  0
total_price                   0
total_freight                 0
total_items                   0
total_weight_g                0
main_category                 0
seller_state                  0
total_payment                 0
max_installments              0
review_score                  0
review_creation_date          0
review_answer_timestamp       0
customer_city                 0
customer_state                0
geolocation_lat               0
geolocation_lng               0
geolocation_city              0
geolocation_state             0
is_late                       0
date                          0
time                          0
order_hour                    0
time_of_day                   0
is_business_hour              0
approval_time_days            0
processing_time_days          0
shipping_time_days            0
total_delivery_days           0
delivery_vs_estimated_days    0
dtype: int64

In [85]:
df = df.drop(columns = ['time' , 'date'])
df.head()

,order_status,total_price,total_freight,total_items,total_weight_g,main_category,seller_state,total_payment,max_installments,review_score,...,geolocation_state,is_late,order_hour,time_of_day,is_business_hour,approval_time_days,processing_time_days,shipping_time_days,total_delivery_days,delivery_vs_estimated_days
0,delivered,29.99,8.72,1.0,500.0,housewares,SP,38.71,1.0,4.0,...,SP,0,10,Morning,1,0.007431,2.366493,6.062650,8.436574,7.107488
1,delivered,118.70,22.76,1.0,400.0,perfumery,SP,141.46,1.0,4.0,...,BA,0,20,Evening,0,1.279745,0.462882,12.039410,13.782037,5.355729
2,delivered,159.90,19.22,1.0,420.0,auto,SP,179.12,3.0,5.0,...,GO,0,8,Morning,1,0.011505,0.204595,9.178113,9.394213,17.245498
3,delivered,45.00,27.20,1.0,450.0,pet_shop,MG,72.20,1.0,5.0,...,RN,0,19,Evening,0,0.012419,3.745833,9.450498,13.208750,12.980069
4,delivered,19.90,8.72,1.0,250.0,stationery,SP,28.62,1.0,5.0,...,SP,0,21,Evening,0,0.042940,0.893113,1.937824,2.873877,9.238171

In [86]:
df.select_dtypes(include=['object', 'category']).nunique()

order_status                   2
main_category                 71
seller_state                  22
review_creation_date         615
review_answer_timestamp    65654
customer_city               3635
customer_state                27
geolocation_city            3762
geolocation_state             27
time_of_day                    4
dtype: int64

In [87]:
# حذف الأعمدة غير الضرورية والتسريبية
# حذف الأعمدة ذات التعددية العالية جداً أو غير الضرورية
columns_to_drop_now = [
    'review_answer_timestamp', 
    'customer_city', 
    'review_creation_date', 
    'geolocation_city'
]

df = df.drop(columns=[col for col in columns_to_drop_now if col in df.columns], errors='ignore')

In [88]:
df.select_dtypes(include=['object', 'category']).nunique()

order_status          2
main_category        71
seller_state         22
customer_state       27
geolocation_state    27
time_of_day           4
dtype: int64

In [89]:
df['main_category'].value_counts()

main_category
bed_bath_table               6337
health_beauty                5971
sports_leisure               5249
computers_accessories        4493
furniture_decor              4270
                             ...
fashion_sport                  15
cds_dvds_musicals              10
la_cuisine                      7
fashion_childrens_clothes       5
security_and_services           2
Name: count, Length: 71, dtype: int64

In [90]:
# 1. تحديد عتبة التكرار (مثلاً: أي فئة تتكرر أقل من عدد معين من المرات، أو أقل من نسبة معينة، سنعتبرها نادرة)


threshold = int(len(df) * 0.01) 

category_counts = df['main_category'].value_counts()
rare_categories = category_counts[category_counts < threshold].index
df['main_category'] = df['main_category'].replace(rare_categories, 'Other')

# التحقق من عدد الفئات بعد الدمج
print("the number of main categories after merging rare values:", df['main_category'].nunique())
print(df['main_category'].value_counts().head(10))

the number of main categories after merging rare values: 22
main_category
Other                    6890
bed_bath_table           6337
health_beauty            5971
sports_leisure           5249
computers_accessories    4493
furniture_decor          4270
housewares               3993
watches_gifts            3783
telephony                2854
auto                     2678
Name: count, dtype: int64

In [91]:
df.select_dtypes(include=['object', 'category']).nunique()

order_status          2
main_category        22
seller_state         22
customer_state       27
geolocation_state    27
time_of_day           4
dtype: int64

## customer_state لديه 27 قيمة، و geolocation_state لديه أيضاً 27 قيمة. غالباً هما نفس الولايات تماماً

In [92]:
(df['customer_state'] == df['customer_state'].str.upper()).value_counts()

customer_state
True    65925
Name: count, dtype: int64

In [93]:
df = df.drop(columns = ['geolocation_state'])

In [94]:
df.select_dtypes(include=['object', 'category']).nunique()

order_status       2
main_category     22
seller_state      22
customer_state    27
time_of_day        4
dtype: int64

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 65925 entries, 0 to 69607
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   order_status                65925 non-null  object
 1   total_price                 65925 non-null  float64
 2   total_freight               65925 non-null  float64
 3   total_items                 65925 non-null  float64
 4   total_weight_g              65925 non-null  float64
 5   main_category               65925 non-null  object
 6   seller_state                65925 non-null  object
 7   total_payment               65925 non-null  float64
 8   max_installments            65925 non-null  float64
 9   review_score                65925 non-null  float64
 10  customer_state              65925 non-null  object
 11  geolocation_lat             65925 non-null  float64
 12  geolocation_lng             65925 non-null  float64
 13  is_late                     65925 non-null  int64
 14  order_hour                  65925 non-null  int32
 15  time_of_day                 65925 non-null  object
 16  is_business_hour            65925 non-null  int32
 17  approval_time_days          65925 non-null  float64
 18  processing_time_days        65925 non-null  float64
 19  shipping_time_days          65925 non-null  float64
 20  total_delivery_days         65925 non-null  float64
 21  delivery_vs_estimated_days  65925 non-null  float64
dtypes: float64(14), int32(2), int64(1), object(5)
memory usage: 11.1+ MB

In [96]:
categorical_cols = ['order_status', 'main_category', 'seller_state', 'customer_state', 'time_of_day']

df = pd.get_dummies(df, columns=categorical_cols, drop_first=True).astype('int')

In [97]:
df.head()

,total_price,total_freight,total_items,total_weight_g,total_payment,max_installments,review_score,geolocation_lat,geolocation_lng,is_late,...,customer_state_RO,customer_state_RR,customer_state_RS,customer_state_SC,customer_state_SE,customer_state_SP,customer_state_TO,time_of_day_Evening,time_of_day_Morning,time_of_day_Night
0,29,8,1,500,38,1,4,-23,-46,0,...,0,0,0,0,0,1,0,0,1,0
1,118,22,1,400,141,1,4,-12,-44,0,...,0,0,0,0,0,0,0,1,0,0
2,159,19,1,420,179,3,5,-16,-48,0,...,0,0,0,0,0,0,0,0,1,0
3,45,27,1,450,72,1,5,-5,-35,0,...,0,0,0,0,0,0,0,1,0,0
4,19,8,1,250,28,1,5,-23,-46,0,...,0,0,0,0,0,1,0,1,0,0

In [98]:
# الأعمدة التالية تحمل "معلومات من المستقبل" (Data Leakage) 
# ولا يجب إعطاؤها للموديل أثناء التدريب لكي يتوقع التأخير بحيادية ومنطقية:
columns_to_drop_for_leakage = [
    'delivery_vs_estimated_days',  # لأنها تحسب الفارق المباشر مع التاريخ الفعلي (تكشف النتيجة المطلوبة للموديل مسبقاً)
    'review_score',                # لأن تقييم الزبون يكتبه ويحدث بعد أن يستلم الطلب وينتهي كل شيء
    'shipping_time_days',          # لأن أيام الشحن الفعلية تعتمد على تاريخ الوصول الحقيقي للزبون (حدث انتهى بالماضي)
    'total_delivery_days'          # لأن إجمالي أيام التوصيل يحسب حتى تاريخ الاستلام الفعلي (معلومة لا تتوفر وقت بدء الطلب)
]

# حذف الأعمدة من الداتا فريم بأمان
df = df.drop(columns=[col for col in columns_to_drop_for_leakage if col in df.columns], errors='ignore')

In [99]:
df.head()

,total_price,total_freight,total_items,total_weight_g,total_payment,max_installments,geolocation_lat,geolocation_lng,is_late,order_hour,...,customer_state_RO,customer_state_RR,customer_state_RS,customer_state_SC,customer_state_SE,customer_state_SP,customer_state_TO,time_of_day_Evening,time_of_day_Morning,time_of_day_Night
0,29,8,1,500,38,1,-23,-46,0,10,...,0,0,0,0,0,1,0,0,1,0
1,118,22,1,400,141,1,-12,-44,0,20,...,0,0,0,0,0,0,0,1,0,0
2,159,19,1,420,179,3,-16,-48,0,8,...,0,0,0,0,0,0,0,0,1,0
3,45,27,1,450,72,1,-5,-35,0,19,...,0,0,0,0,0,0,0,1,0,0
4,19,8,1,250,28,1,-23,-46,0,21,...,0,0,0,0,0,1,0,1,0,0

In [100]:
import numpy as np
import pandas as pd

# 1. تحديد الأعمدة العددية (باستثناء هدفنا is_late وأعمدة الـ One-Hot Encoding الثنائية 0 و 1)
numerical_cols = [
    'total_price', 'total_freight', 'total_items', 'total_weight_g', 
    'total_payment', 'max_installments', 'order_hour', 
    'approval_time_days', 'processing_time_days'
]

# التأكد من أن الأعمدة موجودة فعلاً في الداتا فريم
numerical_cols = [col for col in numerical_cols if col in df.columns]

# 2. فحص الالتواء (Skewness) لكل عمود عددي
skewness_check = df[numerical_cols].skew()
print("--- نسبة الالتواء لكل عمود ---")
print(skewness_check)

# 3. علاج الالتواء العالي باستخدام Log Transformation للأعمدة ذات الالتواء الشديد (مثلاً > 1)
for col in numerical_cols:
    if df[col].skew() > 1:
        # استخدام log1p (أي log(1 + x)) لتجنب مشاكل الصفر
        df[col] = np.log1p(df[col])
        print(f"تم تطبيق Log Transformation على العمود: {col}")

--- نسبة الالتواء لكل عمود ---
total_price             11.012222
total_freight           14.348242
total_items              6.603367
total_weight_g           6.375830
total_payment           10.411743
max_installments         1.619134
order_hour              -0.592869
approval_time_days       5.363821
processing_time_days     2.778130
dtype: float64
تم تطبيق Log Transformation على العمود: total_price
تم تطبيق Log Transformation على العمود: total_freight
تم تطبيق Log Transformation على العمود: total_items
تم تطبيق Log Transformation على العمود: total_weight_g
تم تطبيق Log Transformation على العمود: total_payment
تم تطبيق Log Transformation على العمود: max_installments
تم تطبيق Log Transformation على العمود: approval_time_days
تم تطبيق Log Transformation على العمود: processing_time_days

c:\nn\Lib\site-packages\pandas\core\arraylike.py:396: RuntimeWarning: divide by zero encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\nn\Lib\site-packages\pandas\core\arraylike.py:396: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [101]:
import numpy as np

# 1. استبدال قيم ما لا نهاية (inf) بـ NaN
df.replace([np.inf, -np.inf], np.nan, inplace=True)

In [102]:
from sklearn.preprocessing import StandardScaler

# 1. تحديد الأعمدة العددية التي تحتاج إلى Scaling (نستثني منها الأعمدة الثنائية 0 و 1 والهدف is_late)
scaling_cols = [
    'total_price', 'total_freight', 'total_items', 'total_weight_g', 
    'total_payment', 'max_installments', 'order_hour', 
    'approval_time_days', 'processing_time_days'
]

scaling_cols = [col for col in scaling_cols if col in df.columns]
df.dropna(subset=scaling_cols, inplace=True)

# 2. تطبيق StandardScaler
scaler = StandardScaler()
df[scaling_cols] = scaler.fit_transform(df[scaling_cols])

In [103]:
df.head()

,total_price,total_freight,total_items,total_weight_g,total_payment,max_installments,geolocation_lat,geolocation_lng,is_late,order_hour,...,customer_state_RO,customer_state_RR,customer_state_RS,customer_state_SC,customer_state_SE,customer_state_SP,customer_state_TO,time_of_day_Evening,time_of_day_Morning,time_of_day_Night
0,-1.128238,-1.347764,-0.302295,-0.415316,-1.286826,-0.855889,-23,-46,0,-0.896498,...,0,0,0,0,0,1,0,0,1,0
1,0.359254,0.309391,-0.302295,-0.579118,0.322420,-0.855889,-12,-44,0,0.980125,...,0,0,0,0,0,0,0,1,0,0
2,0.678844,0.062546,-0.302295,-0.543310,0.617716,0.349518,-16,-48,0,-1.271823,...,0,0,0,0,0,0,0,0,1,0
3,-0.666806,0.656818,-0.302295,-0.492668,-0.506156,-0.855889,-5,-35,0,0.792463,...,0,0,0,0,0,0,0,1,0,0
4,-1.565944,-1.347764,-0.302295,-0.923806,-1.655763,-0.855889,-23,-46,0,1.167788,...,0,0,0,0,0,1,0,1,0,0

In [106]:
import joblib

# 1. حفظ الـ Scaler الذي تم عمل fit له على بيانات الـ Train
joblib.dump(scaler, 'my_scaler.pkl')

# 2. حفظ أسماء الأعمدة النهائية للـ Train (مهم جداً لمطابقة أعمدة الـ Validation لاحقاً)
joblib.dump(df.columns.tolist(), 'train_columns.pkl')

# 3. حفظ جدول الـ Train النظيف والجاهز كملف CSV جديد
#df.to_csv('train_cleaned.csv', index=False)

['train_columns.pkl']

In [107]:
df.to_csv('train_cleaned.csv', index=False)

In [108]:
import pandas as pd, joblib

df   = pd.read_csv('train_cleaned.csv')
scaler = joblib.load('my_scaler.pkl')
cols   = joblib.load('train_columns.pkl')

print("✅ Shape:", df.shape)
print("✅ Nulls:", df.isnull().sum().sum())
print("✅ Scaler features:", len(scaler.feature_names_in_))
print("✅ Saved columns:", len(cols))
print("✅ main_category columns:", 
      [c for c in df.columns if 'main_category' in c])

✅ Shape: (65616, 85)
✅ Nulls: 0
✅ Scaler features: 9
✅ Saved columns: 85
✅ main_category columns: ['main_category_auto', 'main_category_baby', 'main_category_bed_bath_table', 'main_category_computers_accessories', 'main_category_consoles_games', 'main_category_cool_stuff', 'main_category_electronics', 'main_category_fashion_bags_accessories', 'main_category_furniture_decor', 'main_category_garden_tools', 'main_category_health_beauty', 'main_category_housewares', 'main_category_luggage_accessories', 'main_category_office_furniture', 'main_category_perfumery', 'main_category_pet_shop', 'main_category_sports_leisure', 'main_category_stationery', 'main_category_telephony', 'main_category_toys', 'main_category_watches_gifts']